name: Trigger OKD Build

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hitelesítés és Build indítása az OKD-n
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.okd.fured.cloud.bme.hu:6443
          openshift_token: ${{ secrets.OKD_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: teszt-hello-world
      
      - name: Start Build
        run: oc start-build test-okd

